# This is a basic workflow to help you get started with Actions
name: Manually trigger workflow

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  repository_dispatch:
    types: [helm-version-release]
    
jobs:
    auto-pull-request:
      name: Package and push Helm chart
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: Checkout branch
          uses: peterjgrainger/action-create-branch@v2.0.1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            branch: 'release-branch-3'

        - name: Verify checkout repo
          run: |
            echo $(ls)
        
        - name: Create commits
          run: |
            git clone https://github.com/cyberark/secrets-provider-for-k8s.git
            echo $(ls)
            helm package secrets-provider-for-k8s/helm/secrets-provider

            git config  --global user.name "sigalsax"
            git config  --global user.email "ssax18@gmail.com"
            git add secrets-provider-1.1.0.tgz
            git commit -m "Test commit"

        - name: Open PR with packaged Helm chart
          uses: vsoch/pull-request-action@1.0.6
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            PULL_REQUEST_FROM_BRANCH: "release-branch-3"
            PULL_REQUEST_BRANCH: master
            PULL_REQUEST_TITLE: "Push Helm chart package for new version release"
            PULL_REQUEST_BODY: "PR for pushing new Helm Chart"
            PULL_REQUEST_ASSIGNEES: sigalsax