# This is a basic workflow to help you get started with Actions
name: Manually trigger workflow

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  repository_dispatch:
    types: [helm-version-release]
    
jobs:
    auto-pull-request:
      name: Package and push Helm chart
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Package and commit Helm chart
          run: |
            git clone https://github.com/cyberark/secrets-provider-for-k8s.git
            helm package secrets-provider-for-k8s/helm/secrets-provider
            rm -r secrets-provider-for-k8s

            git config --global user.name "sigalsax"
            git config --global user.email "ssax18@gmail.com"
            git add secrets-provider-1.1.0.tgz
            git commit -m "Push Helm chart with new version release"

        - name: Create PR
          uses: peter-evans/create-pull-request@v3
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            assignees: sigalsax
            branch: push-helm-chart
            delete-branch: true
            draft: false